<a href="https://colab.research.google.com/github/Abhijit-Mandal/MachineLearning/blob/main/NumpyMasterClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is NumPy?**
Numpy is a library which supports large, multi-dimentional arrays and matrices with large collection of high-level mathematical functions to operate on these arrays.

# **Why NumPy?**


1.   Lists are slow to process. Numpy provides up to 50x faster speed than traditional python lists.
2.   Lots of supporting functions make working with it very easy.
3.   Numpy are faster and more compact than Python lists, it uses less memory to store data. It allows the code to be optimised further.
4. Mathematical operations on NumPy n-Dimension Arrays. Finding elements in NumPy array. More Powerful slicing and Broadcasting functionality. More efficient data Representation. More Convenient. 


Reason for it's fast speed: NumPy is based on C language(Read the documentation). 



# **Ndarray:**

*   An ndarray is a(usually fixed-size) multidimentional container of items of the same type and size.

*  When working with NumPy is simply referred to as an array.

*  It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.

# **Attributes:**

**np.ndim()** - Represents the number of dimensions (axes) of the ndarray.

**np.shape()** - Shape is a tuple of integers representing the dize of the ndarray in each dimension.

**np.size()** - Total number of elements in the ndaraay.

**nparray.dtype** - Returns the data type of the elements of the Numpy Array.

**ndarray.itemsize** - Itemsize returns the size (in bytes) of each element of a Numpy Array. 


In [6]:
import numpy as np


1-D Array

In [7]:
array = np.array([1,2,3,4])

In [8]:
array


array([1, 2, 3, 4])

In [9]:
type(array)

numpy.ndarray

In [28]:
#Tuple to NumPy:

x=(2,4)
y=np.array(x)
print(type(x),type(y))

<class 'tuple'> <class 'numpy.ndarray'>


0-D Array(Scalar):

In [20]:

arr=np.array(12)
print(arr)

12


1-D Array:

In [26]:

arr=np.array([1,2,3])
print(arr.ndim)
print(arr.shape)



1
(3,)


2-D Array:

In [27]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)

2
(2, 3)


Array Multiplication:

In [31]:
arr_1=np.array([3,6,7,5])
arr_2=np.array([4,5,1,7])

arr_3 = arr_1*arr_2
print(arr_3)

[12 30  7 35]


Common functions:




In [36]:
#np.one() Creates array of 1s. Syntax:(rows,col)
np.ones((5,5))
#Using dtype:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.random.rand(5,5)

array([[0.65105221, 0.50924626, 0.56089217, 0.31925491, 0.21855281],
       [0.17651654, 0.22909628, 0.47183172, 0.11985603, 0.51021829],
       [0.11153688, 0.6708657 , 0.98152225, 0.34633982, 0.10822188],
       [0.93424166, 0.14420891, 0.7885412 , 0.34449328, 0.23338527],
       [0.31779729, 0.74890518, 0.45701396, 0.99745683, 0.73821303]])

3-D Arrays:

In [41]:
x = np.array([[
               [1,3],[2,4]
]])
x.shape

(1, 2, 2)

In [43]:
array_3d = np.arange(16).reshape(4,4,1)
print(array_3d)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]]


In [49]:
arr = [[1,2,3],[4,5,6]]

print(np.ndim(arr))
print(np.shape(arr))
print(np.size(arr))
print(array_3d.dtype)
print(array_3d.itemsize)

2
(2, 3)
6
int64
8


In [15]:
#Slicing:
#Start is inclusive and End is exclusive.
#[Start:End] -format of slicing. 
#[Start:End:Step] - Another format of slicing.



In [55]:
name="SIMPLELEARN"
print(name[1:7:2])

lst=[1,2,3,4,5,6,7,8]
print(lst[:9:])

tp1=(1,2,3,4,5,6,7,8)
print(tp1[-1:-9:-1])

IPE
[1, 2, 3, 4, 5, 6, 7, 8]
(8, 7, 6, 5, 4, 3, 2, 1)


numpy.where()
This function either replaces or processes the elemenys of the numpy array that satisfy the condition.

Syntax:
numpy.where(condition[x,y])


In [56]:
arr2=np.array([[-1,2,-3],[4,5,-6]])
b=np.where(arr2<0, "Negative", "Positive")
print(arr2)
print(b)

[[-1  2 -3]
 [ 4  5 -6]]
[['Negative' 'Positive' 'Negative']
 ['Positive' 'Positive' 'Negative']]


Rounding Functions:

numpy.around(): The around() method takes up to three parameters and returns array with all the elements being rounded off to the specified value

In [57]:
in_array=[.5, 2.5, 3.5, 4.5, 10.1]
rounded = np.around(in_array)
print(rounded)

[ 0.  2.  4.  4. 10.]


Statistical Function:

numpy.sum()
The np.sum() used to find the sum of elements over a given axis. The default, axis=None

numpy.mean()
The np.mean() function is used to compute the arithmetic mean along the specifies axis. Returns the average of the array elements. 

In [59]:
lst=[.5, 2.5, 3.5, 4.5, 10.1]

print(np.mean(lst))
print(np.sum(lst))
print(np.std(lst))
print(np.median(lst))


4.220000000000001
21.1
3.2239106687375814
3.5
